# Generated by Django 4.0.5 on 2022-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admininterface', '0002_alter_todo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='schedule',
            field=models.DateField(null=True),
        ),
    ]
