# Generated by Django 4.0.5 on 2022-06-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admininterface', '0003_todo_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='schedule',
            field=models.DateTimeField(null=True),
        ),
    ]
